directories:
  output: release
  buildResources: build
appId: com.yourcompany.jewelryapp
productName: Jewelry Management System
files:
  - filter:
      - dist/**/*
      - backend/dist/run.exe
      - electron-main.cjs
      - package.json
extraResources:
  - from: backend/dist/run.exe
    to: backend/run.exe
win:
  target: nsis
  signtoolOptions:
    publisherName: Metalic
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
nodeGypRebuild: false
buildDependenciesFromSource: false
electronVersion: 36.5.0
