directories:
  output: release
  buildResources: build
appId: com.yourcompany.jewelryapp
productName: Jewelry Management System
files:
  - filter:
      - dist/**/*
      - backend/**/*
      - electron-main.js
      - package.json
      - node_modules/**/*
extraResources:
  - from: backend
    to: backend
win:
  target: nsis
  publisherName: Your Company Name
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 32.3.3
