"""Initial migration

Revision ID: 5a926cb7e44b
Revises: b9dd5c8bb14f
Create Date: 2025-08-31 19:52:40.738849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a926cb7e44b'
down_revision = 'b9dd5c8bb14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_drive_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('backup_time', sa.String(length=5), nullable=True),
    sa.Column('auto_backup_enabled', sa.Boolean(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_drive_auth')
    # ### end Alembic commands ###
